add_newline = true

[character]
success_symbol = "[â¯](bold green)" #
error_symbol = "[â¯](bold red)" 

[username]
disabled = false
show_always = true
style_user = "bold #ff6600"
style_root = "bold blue"
format = "[$user]($style) in "

[directory]
truncation_length = 50
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold #cccc00"

[git_branch]
symbol = ""
style = "bold #00cc00"

[git_status]
conflicted = "${count}="
ahead = "${count}â†‘"
behind = "${count}â†“"
diverged = "${count}â‡•"
untracked = "${count}?"
stashed = "${count}*"
modified = "${count}!"
staged = '[++\($count\)](green)'
renamed = "${count}Â»"
deleted = "${count}âœ˜"
style = "bold #0099ff"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[aws]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ğŸ…° "

[aws.region_aliases]
ap-northeast = "jp"
ap-southeast-2 = "au"
us-east-1 = "va"

[package]
disabled = false