add_newline = true

scan_timeout = 10

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[aws]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "ğŸ…° "

[aws.region_aliases]
ap-northeast = "jp"
ap-southeast-2 = "au"
us-east-1 = "va"

[package]
disabled = false
